// <auto-generated />
namespace MaximCode.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class firstcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "201910281719170_firstcommit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
